add support for mpv internal `mp.input` function
CogentRedTester/mpv-file-browser pull request #112
Opened 2024-09-08 13:34 UTC by dyphire

2024-09-14 05:42 UTC, CogentRedTester requested changes

2024-09-14 05:42 UTC, CogentRedTester commented on main.lua
> +        if user_input_loaded then
Don't add the if statement inside the keybind function, instead define two `mp.add_key_binding` keybinds for each input module and only run one.

2024-09-14 05:42 UTC, CogentRedTester commented on main.lua
> +            input.get({
Again run input.terminate() before input.get to avoid memory leaks.

2024-09-14 05:42 UTC, CogentRedTester commented on modules/utils.lua
> +end
This breaks the [keybind expressions](https://github.com/CogentRedTester/mpv-file-browser/blob/master/docs/custom-keybinds.md#expressions) that use the `input` field because they won't know which module is being used. The [run-statement](https://github.com/CogentRedTester/mpv-file-browser/blob/master/docs/custom-keybinds.md#run-statement-statement) example would break for instance. I'm happy for you to replace `input` in the expressions with the new `mpv.input` for future compatibility, but mpv-user-input still needs to be provided, perhaps through a `user_input` variable instead ([here](https://github.com/CogentRedTester/mpv-file-browser/blob/0c1f7b43dae6b0f0013215877c18632c30733ade/modules/utils.lua#L342)). The documentation will also need to be updated.

2024-09-14 05:53 UTC, CogentRedTester commented on addons/find.lua
> +        query, error = coroutine.yield(
Alternatively, you could use the new `coroutine.callback_t()` function I'm adding in #113:

```lua
    input.get({
        prompt = text .. "\n>",
        id = "find",
        submit = fb.coroutine.callback(),
        opened = fb.coroutine.callback_t(1.5),
    })

    local console_opened = coroutine.yield()
    if not console_opened then return msg.warn('failed to open mp.input') end
    local query = coroutine.yield()
    input.terminate()
```

2024-09-14 06:03 UTC, CogentRedTester commented on addons/find.lua
> +        query, error = coroutine.yield(
Upon inspecting the mp.input code it appears that mp.input discards all the old callbacks when a new `input.get` request is created. This should discard the callback, which should discard the reference to the coroutine, and hence mean no memory leak. But you may still want to add a timeout to opened to provide a useful error message.

2024-09-21 06:56 UTC, dyphire commented on modules/utils.lua
> +end
Didn't notice this usage before, undo change.

2024-11-15 07:26 UTC, CogentRedTester requested changes
Sorry for taking so long to look at this. Just one tiny change and it's good to merge.

2024-11-15 07:26 UTC, CogentRedTester commented on addons/find.lua
> +    version = "1.4.0"
The version field is for the API version that the addon requires, not a version number for the addon itself (this is a little misleading I admit).

```suggestion
    version = "1.3.0"
```

2024-11-16 01:08 UTC, CogentRedTester approved these changes

2024-11-16 01:08 UTC, merged