Fix match between uppercase and lowercase of extensions
CogentRedTester/mpv-file-browser pull request #47
Opened 2022-04-14 19:40 UTC by dyphire

2022-04-21 07:27 UTC, CogentRedTester requested changes
Good change, I mostly just have some syntax changes I'd like to keep consistent with the rest of the script. I also have a small logic change suggestion for the whitelist/blacklist.

2022-04-21 07:27 UTC, CogentRedTester commented on file-browser.lua
> +    return string.lower(filename):match("%.([^%./]+)$") or def
```suggestion
    return filename:lower():match("%.([^%./]+)$") or def
```

Using this syntax, it matches the syntax I've used elsewhere.

2022-04-21 07:27 UTC, CogentRedTester commented on file-browser.lua
> +    return string.lower(filename):match("^(%a%w*)://") or def
```suggestion
    return filename:lower():match("^(%a%w*)://") or def
```

2022-04-21 07:27 UTC, CogentRedTester commented on file-browser.lua
> +function API_mt.remove_parseable_extension(ext) parseable_extensions[string.lower(ext)] = nil end
```suggestion
function API_mt.register_parseable_extension(ext) parseable_extensions[ext:lower()] = true end
function API_mt.remove_parseable_extension(ext) parseable_extensions[ext:lower()] = nil end
```

2022-04-21 07:27 UTC, CogentRedTester commented on file-browser.lua
> +        extensions[string.lower(compatible_file_extensions[i])] = true
There is no need for this, the compatible_file_extension list is always in lowercase

2022-04-21 07:27 UTC, CogentRedTester commented on file-browser.lua
> +        sub_extensions[string.lower(subtitle_extensions[i])] = true
There is also no need for this, the subtitle extensions cannot be user set, so they will always be lowercase.

2022-04-21 07:27 UTC, CogentRedTester commented on file-browser.lua
>      for str in string.gmatch(o.extension_whitelist, "([^"..pattern_escape(o.root_seperators).."]+)") do
```suggestion
    for str in string.gmatch(o.extension_whitelist:lower(), "([^"..pattern_escape(o.root_seperators).."]+)") do
```

Change the whole option string to lowercase instead of doing it for every individual extension

2022-04-21 07:27 UTC, CogentRedTester commented on file-browser.lua
>      for str in string.gmatch(o.extension_blacklist, "([^"..pattern_escape(o.root_seperators).."]+)") do
```suggestion
    for str in string.gmatch(o.extension_blacklist:lower(), "([^"..pattern_escape(o.root_seperators).."]+)") do
```
Same here

2022-04-21 13:22 UTC, dyphire commented on file-browser.lua
> +    return string.lower(filename):match("%.([^%./]+)$") or def
Done.

2022-04-21 13:22 UTC, dyphire commented on file-browser.lua
> +    return string.lower(filename):match("^(%a%w*)://") or def
Done.

2022-04-21 13:22 UTC, dyphire commented on file-browser.lua
> +function API_mt.remove_parseable_extension(ext) parseable_extensions[string.lower(ext)] = nil end
Done.

2022-04-21 13:22 UTC, dyphire commented on file-browser.lua
>      for str in string.gmatch(o.extension_whitelist, "([^"..pattern_escape(o.root_seperators).."]+)") do
Done.

2022-04-21 13:22 UTC, dyphire commented on file-browser.lua
>      for str in string.gmatch(o.extension_blacklist, "([^"..pattern_escape(o.root_seperators).."]+)") do
Done.

2022-04-21 13:25 UTC, dyphire commented on file-browser.lua
> +        extensions[string.lower(compatible_file_extensions[i])] = true
Just to prevent someone from directly modifying the extended content in the script. 
Restore.

2022-04-21 13:25 UTC, dyphire commented on file-browser.lua
> +        sub_extensions[string.lower(subtitle_extensions[i])] = true
Restore.

2022-04-26 07:58 UTC, CogentRedTester approved these changes

2022-04-26 08:00 UTC, CogentRedTester requested changes
Everything looks good, but I just merged #46, so you'll need to resolve the conflicts. Try to avoid a merge commit if you can, it would probably be easiest to undo this commit, pull the changes from master, and just manually edit these 6 lines again.

2022-04-26 09:06 UTC, dyphire commented
> Everything looks good, but I just merged #46, so you'll need to resolve the conflicts. Try to avoid a merge commit if you can, it would probably be easiest to undo this commit, pull the changes from master, and just manually edit these 6 lines again.

Great. Let's finish it.

2022-04-26 09:06 UTC, closed without merging