Realize loading external audio track, add the black-and-white list for audio extensions and subtitle extensions.
CogentRedTester/mpv-file-browser pull request #50
Opened 2022-04-26 16:00 UTC by dyphire

In fact, I'm not sure that subtitle files need a extensions blacklist.

2022-04-27 10:18 UTC, CogentRedTester requested changes

2022-04-27 10:18 UTC, CogentRedTester commented on file-browser.lua
> +
There's a bug here which requires a change in logic for this function. If you don't also add the whitelisted sub/audio extensions to the main extensions table then they may never appear in the browser. But if we blacklist a specific extension (say an audio file) from the custom audio behaviour, then we still want it to appear in the browser to be loaded normally, so we can't just do what we did with the main whitelist/blacklist.

Essentially we need to place this section just below where we iterate through the `subtitle_extensions` and `audio_extensions_list` arrays. And we need to delay setting the fields in the `extensions` table until a separate loop.

To give an example for just subtitles we need to do something like:
```lua
    --setting up subtitle extensions
    for i = 1, #subtitle_extensions do
        sub_extensions[subtitle_extensions[i]] = true end
    for str in string.gmatch(o.sub_extension_whitelist:lower(), "([^"..API.pattern_escape(o.root_seperators).."]+)") do
        sub_extensions[str] = true end
    for str in string.gmatch(o.sub_extension_blacklist:lower(), "([^"..API.pattern_escape(o.root_seperators).."]+)") do
        sub_extensions[str] = nil end

    --adding subtitle extensions to the main extension list
    for ext in pairs(sub_extensions) do
        extensions[ext] = true end
```

Also the space usage of these for loops is getting ridiculous so use the compact styling I used there.

2022-04-27 10:18 UTC, CogentRedTester commented on file-browser.lua
> +}
I like the name `audio_extension_list`, but it and the equivalent subtitle list needs to have consistent naming. Change the subtitle variable name to `subtitle_extension_list`.

2022-04-27 10:18 UTC, CogentRedTester commented on file-browser.lua
> +        mp.commandv("audio-add", path, flag == "replace" and "auto" or "cached" or "select")
Why is the behaviour of these flags different?

2022-04-27 10:18 UTC, CogentRedTester commented on file_browser.conf
> +#note that this will override the audio whitelist option above
```suggestion
#note that this will override the sub whitelist option above
```

2022-04-27 10:18 UTC, CogentRedTester commented on file_browser.conf
> +#extensions are separated with the root seperators, do not use any spaces
```suggestion
#files with these extensions will be added as additional audio tracks instead of appended to the playlist
#extensions are separated with the root seperators, do not use any spaces
```

2022-04-27 10:18 UTC, CogentRedTester commented on file_browser.conf
> +#add file extensions to this list to disable default filetypes for audio track
```suggestion
#disable the default audio extensions - mka dts dtshd dts-hd truehd true-hd
```

2022-04-27 10:18 UTC, CogentRedTester commented on file_browser.conf
> +#adding a file extension to this list will add it to the extension whitelist of subtitle
```suggestion
#files with these extensions will be added as additional audio tracks instead of appended to the playlist (which doesn't work with subtitles)
```

2022-04-27 10:18 UTC, CogentRedTester commented on file_browser.conf
> +#add file extensions to this list to disable default filetypes for subtitle
```suggestion
#disable the default sub extensions - etf etf8 utf-8 idx sub srt rt ssa ass mks vtt sup scc smi lrc pgs
```

2022-04-27 10:18 UTC, CogentRedTester commented on file_browser.conf
>  #note that this will override the whitelist option above
```suggestion
#note that this will override all whitelist options above and below
```

2022-04-27 11:52 UTC, dyphire commented on file-browser.lua
> +
You're right. I missed this.

Dnoe

2022-04-27 11:52 UTC, dyphire commented on file-browser.lua
> +}
Done.

2022-04-27 11:53 UTC, dyphire commented on file_browser.conf
> +#adding a file extension to this list will add it to the extension whitelist of subtitle
Is there a issue with the changes here?

2022-04-27 12:35 UTC, dyphire commented on file-browser.lua
> +        mp.commandv("audio-add", path, flag == "replace" and "auto" or "cached" or "select")
> Why is the behaviour of these flags different?

```
auto:   Don't select the file
select: Select the file immediately 
cached: Select the file. If a file with the same filename was already added, that one is selected, instead of loading a duplicate entry.
```

Referring to the official documentation, it seems that the cached flag should be the preferred choice.

However, when I tested loading external audio tracks, I found that the default switching behavior will lead to video jamming. At this time, it can only be fixed by switching audio tracks or seek.

Therefore, for audio files, we should use the auto flag for better compatibility.

2022-04-27 12:41 UTC, dyphire commented on file-browser.lua
> +
Done.

2022-04-29 11:11 UTC, CogentRedTester commented
I want to do some experimentation and testing before merging this PR. If need be I'd rather forgo the cache optimisation in order to keep the overall behaviour consistent, but I'll let you know. I'm a little short on time right now, but everything else in this PR seems to be looking good. Feel free to ping me in a couple of weeks if I haven't gotten back to you.

2022-05-07 07:48 UTC, CogentRedTester requested changes
Once those suggestions I made are committed or rebutted then I'd say we're done. Sorry for the delay.

2022-05-07 07:48 UTC, CogentRedTester commented on file-browser.lua
> +        mp.commandv("audio-add", path, flag == "replace" and "auto" or "cached" or "select")
I don't have any problems when switching to new audio tracks. I got a brief freeze when I loaded a file that was the wrong length, but it quickly fixed itself. Can you give more details about what's going wrong in your case?

2022-05-07 07:48 UTC, CogentRedTester commented on file-browser.lua
> +        mp.commandv("audio-add", path, flag == "replace" and "auto" or "cached" or "select")
```suggestion
        mp.commandv("sub-add", path, flag == "replace" and "select" or "auto")
    elseif audio_extensions[ API.get_extension(item.name, "") ] then
        mp.commandv("audio-add", path, flag == "replace" and "select" or "auto")
```

For the time being I'd like to stick to the original behaviour. I like the idea of using the cached option, but I'd like to put it behind another script-opt, I'd also like for it to be done in a different commit/PR (I might do it myself once this is merged). If certain versions of mpv or certain playback options cause a freeze when using the audio-add command, then that's not our fault, I don't want to make the behaviour of this script inconsistent because of a bug that could be fixed at any time.

What you had here was bugged anyway, since the `auto` option for `sub-add` and the `select` option for `audio-add` would never be triggered due to Lua's ternary statement behaviour.

2022-05-07 07:48 UTC, CogentRedTester commented on file-browser.lua
> +function API.get_audio_extensions() return API.copy_table(audio_extensions) end
This will need to be added to the addon API documentation. However, I would like to do that myself as part of a batch API update, so this is done.

2022-05-07 07:48 UTC, CogentRedTester commented on file-browser.lua
> +    --audio_track extensions list directly. A semicolon separated list of extensions without spaces
```suggestion
    --files with these extensions will be added as additional audio tracks instead of appended to the playlist
```

2022-05-07 07:48 UTC, CogentRedTester commented on file-browser.lua
> +    --subtitle extensions list directly. A semicolon separated list of extensions without spaces
```suggestion
    --files with these extensions will be added as additional subtitle tracks instead of appended to the playlist
```

2022-05-07 07:48 UTC, CogentRedTester commented on file_browser.conf
> +##files with these extensions will be added as additional audio tracks instead of appended to the playlist
```suggestion
#files with these extensions will be added as additional audio tracks instead of appended to the playlist
```

2022-05-07 07:48 UTC, CogentRedTester commented on file-browser.lua
> +    --add extra audio_track file extensions
```suggestion
```

2022-05-07 07:48 UTC, CogentRedTester commented on file-browser.lua
> +    --add extra subtitle file extensions
```suggestion
```

2022-05-07 07:48 UTC, CogentRedTester commented on file-browser.lua
> +    --add extra audio_track file extensions
Lets just save some space and remove some of these comments. The main documentation is in the conf file anyway.

2022-05-07 08:28 UTC, CogentRedTester approved these changes

2022-05-07 08:28 UTC, dyphire commented on file-browser.lua
> +        mp.commandv("audio-add", path, flag == "replace" and "auto" or "cached" or "select")
I agree with you that this is a probably issue of mpv or ffmpeg, and should be reported and waiting for their repair. 
Let's return to original behavior.

2022-05-07 08:29 UTC, dyphire commented on file-browser.lua
> +    --audio_track extensions list directly. A semicolon separated list of extensions without spaces
Done.

2022-05-07 08:31 UTC, CogentRedTester commented
If you're ready I'm happy to commit now.

2022-05-07 08:34 UTC, dyphire commented
> If you're ready I'm happy to commit now.

I am quite satisfied with the current changes.
So yes, everything is ready.

2022-05-07 08:36 UTC, merged

2022-05-07 08:43 UTC, CogentRedTester commented
Nice work, sorry it took me so long to review this.